processed 7 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-41:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5), object(1,6), object(1,7)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 18794800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 43:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 3, lines 45-47:
//# programmable --sender A --inputs 500 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4, line 49:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 51-55:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "data": [
      {
        "coinType": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI",
        "coinObjectId": "0x2834d85dbfefdcd66f04811231ba818893793e83a895d53402fd99e132e36562",
        "version": "4",
        "digest": "8RtG7ew6uomy64p75gW8bysfjJbEVjNgr7xhsr7hVN3j",
        "balance": "299999977183716",
        "previousTransaction": "6xiXsRVayb3NGPmuDkoy95dVrDeeSmKEaTZo2hSDxCGJ"
      },
      {
        "coinType": "0xf5ce206aa1fffb93935caae7f35123bf471173bc2b42f77c66a035043060c071::fake::FAKE",
        "coinObjectId": "0x1c06fe536adc913b33082885c9deb5243f617a4810f4d6895d9ca78c5613b041",
        "version": "2",
        "digest": "CCUct1nMqHYvTWspP59DUSYH1sYYW129ckUuksahU9G",
        "balance": "3000",
        "previousTransaction": "4Mpg2JTgZa2pt8akvsiqazRZohAbsVBUVVemra6eAR3d"
      },
      {
        "coinType": "0xf5ce206aa1fffb93935caae7f35123bf471173bc2b42f77c66a035043060c071::fake::FAKE",
        "coinObjectId": "0x78ebc8177cb90d983dcafc9c5541a20dc33f44b6058be96dbb3069202532a20a",
        "version": "2",
        "digest": "BmJ8PfWvoR8xKBLFGhtfCewi9w13tjCTwwvvQ5k7xkmd",
        "balance": "4000",
        "previousTransaction": "4Mpg2JTgZa2pt8akvsiqazRZohAbsVBUVVemra6eAR3d"
      },
      {
        "coinType": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI",
        "coinObjectId": "0xbeeb33d9e6850f587fb7e155c0b8d4149b8ffac939b466a1403b094b992effb3",
        "version": "4",
        "digest": "ApA97uYGxQu6qdxDB7aFThNxrQHJDFZaXAX285h31DJ9",
        "balance": "500",
        "previousTransaction": "6xiXsRVayb3NGPmuDkoy95dVrDeeSmKEaTZo2hSDxCGJ"
      },
      {
        "coinType": "0xf5ce206aa1fffb93935caae7f35123bf471173bc2b42f77c66a035043060c071::fake::FAKE",
        "coinObjectId": "0xc6e3d02b9a0160f25578ec0f8f6de719fa642f647179dfbf057ff857d9f5c975",
        "version": "2",
        "digest": "Aje2LLNb1R3tpLnFcZ3P1UYs8afQ9XQhPKatPvp9LD6V",
        "balance": "100",
        "previousTransaction": "4Mpg2JTgZa2pt8akvsiqazRZohAbsVBUVVemra6eAR3d"
      },
      {
        "coinType": "0xf5ce206aa1fffb93935caae7f35123bf471173bc2b42f77c66a035043060c071::fake::FAKE",
        "coinObjectId": "0x89937febb73cf783a63724b12bdfdc8112aeaac78466b463710506aa72624317",
        "version": "2",
        "digest": "DEX2jGJyLHDkDSDNVA5iL8uubMZrk7SjDShPSdyVBsQN",
        "balance": "2",
        "previousTransaction": "4Mpg2JTgZa2pt8akvsiqazRZohAbsVBUVVemra6eAR3d"
      }
    ],
    "nextCursor": "eyJvYmplY3RfaWQiOiIweDg5OTM3ZmViYjczY2Y3ODNhNjM3MjRiMTJiZGZkYzgxMTJhZWFhYzc4NDY2YjQ2MzcxMDUwNmFhNzI2MjQzMTciLCJjcF9zZXF1ZW5jZV9udW1iZXIiOjEsImNvaW5fYmFsYW5jZV9idWNrZXQiOjB9",
    "hasNextPage": false
  }
}

task 6, lines 57-61:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "data": [
      {
        "coinType": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI",
        "coinObjectId": "0xfdc25bc3b2d2b3664199d08f5275c3a6bb360b0629ab5784672f083149163417",
        "version": "1",
        "digest": "4hY6HbcSgDuyD5TcKhxom1cPPdPTQtcoNUStc8BYoZt5",
        "balance": "300000000000000",
        "previousTransaction": "9YaSDYB2hY7DwGwATGe2y5D4d8BwtQjE8bj2wRQecqnr"
      },
      {
        "coinType": "0xf5ce206aa1fffb93935caae7f35123bf471173bc2b42f77c66a035043060c071::fake::FAKE",
        "coinObjectId": "0x432c7c87c609b5c9e4cf20816a4d293ba11fd6c13613a13ffcc4b17220779072",
        "version": "3",
        "digest": "Gmf4Ee7E7fptNN4CQGrSYSQkp53bSpRhB7n3ZwggGbv7",
        "balance": "5000",
        "previousTransaction": "3Eua5XMZMGKPyYtTYdT55ppG3i2Gc25zfrBYFuiVi5Y4"
      }
    ],
    "nextCursor": "eyJvYmplY3RfaWQiOiIweDQzMmM3Yzg3YzYwOWI1YzllNGNmMjA4MTZhNGQyOTNiYTExZmQ2YzEzNjEzYTEzZmZjYzRiMTcyMjA3NzkwNzIiLCJjcF9zZXF1ZW5jZV9udW1iZXIiOjEsImNvaW5fYmFsYW5jZV9idWNrZXQiOjN9",
    "hasNextPage": false
  }
}
